### ISSUE TITLE
Security consideration on custom subdomains

### ISSUE THREAD

**Issue by dariox86** [loophole/cli#156]
**Is your feature request related to a problem? Please describe.**
When deleting hidden folder .loophole, a new certificate can be readily generated for the chosen subdomain. Does this mean that the certificate is stored somewhere on Loophole's servers? If this is the case, then the user has to put trust in Loophole as a service.

**Describe the solution you'd like**
If what I stated in the first point is true, while to option to recover the certificate can be convenient for some, a zero knowledge option is desirable for those who do want to control their chain of trust.

**Describe alternatives you've considered**
Adding an option to request a Let's Encrypt certificate that lives only on the machine of the user. Losing the certificate means that the user is responsible for the loss of data, but the chain of trust is shorter.

**Comment by 0x7f** [comment]
Hi @dariox86 I really appreciate your thoughts about loophole privacy. Because that's what was our main goal as well when building loophole.

The system is designed in a way that the loophole backend service is not able to inspect any user's traffic. The SSL certificate is generated on the client machine and never leaves it. Our servers are just reading the [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) field in the SSL handshake to know to which tunnel to route the traffic to. But the server is unable to actually perform the handshake, as the SSL certs do not exist on the server. Only your computer with the loophole cli and the according SSL cert can perform the handshake.

We plan to write a blog post about the technical details. What I wrote above is the core of it though. Will keep you posted when we post it ;)

Does this answer your question?

**Comment by 0x7f** [comment]
One additional remark: yes, when you delete the `~/.loophole/certs` folder, the cli will acquire a new certificate from Let's Encrypt when starting the tunnel again. The certificate is not cached anywhere, also not on our servers.

**Comment by dariox86** [comment]
Thank you, @0x7f. I apologize for incorrectly wording my considerations. To put it simply: let's say I have a custom subdomain _customname.loophole.site_. If I delete my certificate by accident, all that is needed to recover the certificate is just my email and password used to signup to Loophole. If an attacker finds a way into your systems to recover user credentials, all that is needed to impersonate me with my subdomain is my email and password regardless of the certificate. That would put another element, in this case Loophole as a service, in the chain of trust. Is this correct?

**Comment by Morishiri** [comment]
@dariox86 the subdomain is actually being reserved for your account. No-one else can take your subdomain when you were first to obtain it. It is bound to your account.

**Comment by dariox86** [comment]
I checked once more. You are right. Thank you for your patience.
