### ISSUE TITLE
Cannot rehuse same hostname doing logout/login

### ISSUE THREAD

**Issue by FabianSilva** [loophole/cli#158]
**Describe the bug**
error 500 logged out and log in in (same or another pc)
I logged out from one pc, logged in from another, try to use 
`loophole http port --hostname xxxxxxxxxx` same as before and give me a error 500

**To Reproduce**
log in (github account)
`loophole http port --hostname xxxxxxxxxx` 
log out

log in (github account) in another pc
`loophole http port --hostname xxxxxxxxxx` 
error 500 appears

log in (github account) in same pc
`loophole http port --hostname xxxxxxxxxx` 
error 500 appears

**Expected behavior**
be able to use domain or a least a message telling me that cannot use same domain again...

**Screenshots**
```
Registering your domain... Error! Request Error (500): Internal server error - Something unexpected happened, please let developers know
11:05PM ERR Request ended with status code 500
11:05PM ERR Internal server error
11:05PM ERR Details: Something unexpected happened, please let developers know
11:05PM ERR Please fix the above issue and try again
11:05PM FTL Request Error (500): Internal server error - Something unexpected happened, please let developers know
```

**Environment**
 - OS: Windows 10
 - Version loophole-cli_1.0.0-beta.14_windows_64bit

**Additional context**
I not remember if I used github or google to login first time... now I logged in with github... can be that using different login, when try to use same domain give the 500 error?

**Comment by Morishiri** [comment]
Hello @FabianSilva, that's the main feature that you can reserve the domain name and re-use it later. I chcked the logs and we indeed are getting "Name already taken" errors. Maybe you e.g. first used google and then github to login? I can check and provide more information if you provide me with a domain or the user details (can be sent on our loophole@main.dev support email if you don't want to share the details publicly).

We consolidate the accounts only if they have the same email. If you google account and github account have different emails attached, you cannot use them to access the same reserved domain. Email is the main parameter taken into account here.

---

Beside the core of the problem: 500 is a temporary error caused by our API migration, normally you'd get correct "Name already taken" error, we'll restore proper error mapping when we're done with the migration.
