### ISSUE TITLE
Account registration is broken

### ISSUE THREAD

**Issue by knrdl** [loophole/cli#183]
```
$ loophole account login -v  
7:58PM FTL Error obtaining device code: There was a problem executing request for device code
```
Error appears at [`internal/pkg/token/token.go:62`](https://github.com/loophole/cli/blob/master/internal/pkg/token/token.go#L62)
because OAuth provider is dead: https://loophole.eu.auth0.com/oauth/device/code returns "Not found."

**Comment by Morishiri** [comment]
Hello @knrdl, I just managed to successfully log in. 

https://loophole.eu.auth0.com/oauth/device/code returns Not found for `GET` requests, because it's `POST` route.

You can see we're executing POST in https://github.com/loophole/cli/blob/master/internal/pkg/token/token.go#L54

```
➜  ./loophole account login 
Please open https://loophole.eu.auth0.com/activate and use ZZZZ-YYYY code to log in
7:59AM INF Logged in successfully
```

or with `-v`:
```
➜  ./loophole account login -v
Please open https://loophole.eu.auth0.com/activate and use ZZZZ-YYYY code to log in
8:01AM DBG Polling with interval interval=5000 unit=second
8:01AM DBG Error response error=authorization_pending errorDescription="User has yet to authorize device code."
8:01AM DBG Error response error=authorization_pending errorDescription="User has yet to authorize device code."
8:01AM INF Logged in successfully
```

Can you please try again? May be that Auth0 had some issue at that time?

**Comment by knrdl** [comment]
My mistake!
The docker container I tested loophole in used ubuntu:22.04 as base image. It lacks the current ca certificates. 
`apt update && apt install ca-certificates` resolved the issue

**Comment by Morishiri** [comment]
Great to hear that!
