### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by Rix565** [loophole/cli#193]
**Is your feature request related to a problem? Please describe.**
Well, I wanna use my Revolt.chat instance outside of localhost, but since it is using a ws:// server for live posting, logging in with the official Revolt.chat client just throws "An error has occured".
**Describe the solution you'd like**
I want a full websocket support on the backend, so that I can use my Revolt.chat instance correctly (not just parts of it :') )

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Morishiri** [comment]
We support websockets since almost beginning of loophole's existance.

To be sure, I created demo websocket server and client from the examples on https://github.com/websockets/ws and it worked.

There must be something else going on.
1. I don't know the specification of Revolt.Chat, but does it use the same port for websocket?
2. Maybe try using `wss` instead of `ws`.

**Comment by Morishiri** [comment]
Closing the issue, in case there are further questions - feel free to ask.
