### ISSUE TITLE
Add option to serve a path instead of a port

### ISSUE THREAD

**Issue by 0x7f** [loophole/cli#58]
**Is your feature request related to a problem? Please describe.**

One of my main use cases for loophole is to serve static files from a local directory. To do so, I use `python -m SimpleHTTPServer 8080` to start a simple http server serving the current dir. But it would be super cool to have this integrated into the cli.

**Describe the solution you'd like**

It would be really cool if I could provide a path (usually just `.`) instead of a port when starting the cli. In this case, it is not forwarding the requests to the upstream server, but serving the files directly.

I can imagine that additional options will be needed (default index and error document). More sophisticated options can be added later, imho (follow redirects, mime type settings, etc.).

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by Morishiri** [comment]
For his we need to re-think the way we start the app.

Currently we use
```
loophole <port>
```

to start it. I propose to put it under some sub-command with separate options.

e.g.
```
loophole port 3000
```
```
loophole dir <path>
```

This would make it easier and avoid so many `if` in the code.

**Comment by 0x7f** [comment]
I would optimize for the user instead of the developer 😅 To me, it is easier to just provide the path or port. On the other hand, what if there is a folder named `account` (like a sub-command) or if there is folder named `8000` (like a port)? For a long version I would prefer sth like `loophole open --dir <dir>`, but we said, we wanted to have nice short version...

**Comment by Morishiri** [comment]
I started thinking wider, it would be great to have short command like we have right now. Just `loophole 8000` is great, but:
- if we want to extend it to also work for directories then the process would be as follow:
    - try to parse first arg as `int`, if it worked go the port flow
    - if it didn't try to parse it as path (what if you wanted to expose dir called `1234`? :P)
    - establish tunnel

When we will start adding functionalities like `basic auth`, `raw TCP tunnel` we wil lend up with a lot of `--options` and I would like to avoid that. That's why I would like to end up with some categories for commands. E.g.:
- `loophole serve http 3000`
- `loophole serve port 22`
- `loophole serve path/dir ./my-dir`
- `loophole account login`
- `loophole account logout`
- `loophole completion bash`
etc

But it all seems so long and hard to type :/

**Comment by Morishiri** [comment]
But additionally considering interactive mode it somehow starts to make sense, because typing just `loophole` will open the interactive menu

**Comment by denny241** [comment]
Yeah, without interactive mode coming up, I would have argued that the user experience is getting to convoluted. But with it, it should be fine

**Comment by Morishiri** [comment]
Done
