### ISSUE TITLE
allow --hostname string to contain delimiters

### ISSUE THREAD

**Issue by AdamJel** [loophole/cli#89]
Hi,

I discovered loophole today, tested it shortly and I am very excited about it. Great work, guys!! 👍 

It would be nice, if the `--hostname` flag would accept some delimiters, such as dot (`.`) so that the whole url could be `https://string1.string2.stringN.loophole.site`. This would allow instinctive fine-graining of url, such as `org.appname.loophole.site`, `org.app2.loophole.site, etc`..

**Comment by Morishiri** [comment]
Hello, I'm really happy that you liked it 👍🏻

I will investigate about your proposal, but at first glance I think it should be possible :)

**Comment by 0x7f** [comment]
Hi Adam, thank you very much for reporting this good idea. We definitely see the point and discussed this feature in-depth internally. Right now, we decided to not implement `.` as a delimiter. Mostly because we can not predict the implications on the DNS in the future, but most importantly that we see a high probability for phishing attacks with this (e.g. someone hosting `login.someimportantsizte.com.loophole.site` to trick users into entering credentials).

At the moment, custom domains are allowed to contain lower case chars and numbers, only. We will extend this list to include `-`. Hope this delimiter is fine for you?

**Comment by AdamJel** [comment]
@0x7f  Thank you for considering the feature. I understand the reason not to allow dot delimiter for now. It would be somewhat better then the `-`, but `-` is good enough. It definitely does the job of nicely partitioning url.
