### ISSUE TITLE
On raspberry pi gives error -bash: loophole: command not found

### ISSUE THREAD

**Issue by ndrdmarshmallow** [loophole/cli#92]
On raspberry pi I am getting error as below 

```
pi@rasp:~/ngrok $ ls
LICENSE  README.md  loophole  loophole_1.0.0-beta.12_linux_arm64.tar.gz  ngrok
pi@rasp:~/ngrok $ loophole account login
-bash: loophole: command not found
pi@rasp:~/ngrok $ cd
pi@rasp:~ $ 
```

**Comment by Morishiri** [comment]
Hey,

to be able to use it without adding to `$PATH` you need to use `loophole` as `./loophole` (`./` means current directory you're in).

Otherwise, to run it as `loophole` you need to have the binary in `$PATH`, so here you have 2 options:
- add the containing directory to your `$PATH` (`export PATH=$PATH:/path/to/loophole/directory`)
- move `loophole` binary to one of the directories already existing in `$PATH` (e.g. `/use/local/bin`)

More information on `$PATH` env variable can be found in e.g. this `stackoverflow` answer: https://stackoverflow.com/a/26962251/5069352

We will however update `README` to mention the usage as `./loophole`.

Thank you for reporting that :)
